/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FormAdmin;


import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import main.Form_login1;
import main.Form_login1;
import main.MenuItem;




/**
 *
 * @author Lenovo
 */
public class Menu_Admin extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form Menu_Utama
     * @param P
     */
    public Menu_Admin() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
       
        excecute();
        
    }

  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pn_sidebar2 = new javax.swing.JPanel();
        pn_menu = new javax.swing.JPanel();
        pn_content = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 51, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setText("ini Log-out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(869, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pn_sidebar2.setBackground(new java.awt.Color(255, 255, 255));

        pn_menu.setBackground(new java.awt.Color(255, 255, 255));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout pn_sidebar2Layout = new javax.swing.GroupLayout(pn_sidebar2);
        pn_sidebar2.setLayout(pn_sidebar2Layout);
        pn_sidebar2Layout.setHorizontalGroup(
            pn_sidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sidebar2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pn_sidebar2Layout.setVerticalGroup(
            pn_sidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sidebar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );

        getContentPane().add(pn_sidebar2, java.awt.BorderLayout.LINE_START);

        pn_content.setBackground(new java.awt.Color(255, 255, 255));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_contentLayout = new javax.swing.GroupLayout(pn_content);
        pn_content.setLayout(pn_contentLayout);
        pn_contentLayout.setHorizontalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_contentLayout.setVerticalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        getContentPane().add(pn_content, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pn_utama.add(new konten());
        pn_utama.repaint();
        pn_utama.revalidate();
       
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //         pn_utama.removeAll();
        //         pn_utama.repaint();
        //         pn_utama.revalidate();
        Form_login1 login = new Form_login1();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu_Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_sidebar2;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables

    private void excecute() {
//        icon
       ImageIcon iconHome = new ImageIcon(getClass().getResource("/gambar/home3.png"));
       ImageIcon iconProfil = new ImageIcon(getClass().getResource("/gambar/profile1.png"));
       ImageIcon iconUser = new ImageIcon(getClass().getResource("/gambar/user.png"));
       ImageIcon iconProduk = new ImageIcon(getClass().getResource("/gambar/produk2.png"));
       ImageIcon iconRiwayat = new ImageIcon(getClass().getResource("/gambar/transaksi.png"));
//     ImageIcon iconBarang = new ImageIcon(getClass().getResource("/gambar/home.png"));

//        submenu
//        MenuItem produk1 = new MenuItem(null, true,iconBarang, "produk1", null);  
//        MenuItem produk2 = new MenuItem(null, true,iconBarang, "produk2", null);  
       

        MenuItem menuHome = new MenuItem(iconHome, false,null, "Home", new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               pn_utama.removeAll();
               pn_utama.add(new konten());
               pn_utama.repaint();
               pn_utama.revalidate();  }
       });
        
        MenuItem menuProfil = new MenuItem(iconProfil, false,null, "Profil",new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               pn_utama.removeAll();
               pn_utama.add(new ProfileAdmin());
               pn_utama.repaint();
               pn_utama.revalidate();  }
       }); 
        MenuItem menuUser = new MenuItem(iconUser, false,null, "User", new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               pn_utama.removeAll();
               pn_utama.add(new User());
               pn_utama.repaint();
               pn_utama.revalidate();  }
       });  
        MenuItem menuProduk = new MenuItem(iconProduk, false,null, "Produk", new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               pn_utama.removeAll();
               pn_utama.add(new Produk());
               pn_utama.repaint();
               pn_utama.revalidate();  
           }
       }); 
            
        
        MenuItem menuReport= new MenuItem(iconRiwayat, false,null, "Riwayat", null);  
        addMenu(menuHome,menuProfil,menuUser,menuProduk,menuReport);
    }
    
   private void addMenu(MenuItem... menu) {
    for (MenuItem item : menu) {
        pn_menu.add(item);
        ArrayList<MenuItem> subMenu = item.getSubMenu();
        for (MenuItem m : subMenu) {
            addMenu(m);  // Rekursif menambahkan submenu
        }
    }
    pn_menu.revalidate();  // Memastikan layout diperbarui
    pn_menu.repaint();     // Menyegarkan tampilan
}
}
    

