
package FormAdmin;

import dao.DAO_User;
import java.awt.PopupMenu;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.model_user;
import service.service_user;
import tablemodel.tablemod_user;


/**
 *
 * @author Lenovo
 */
public class User extends javax.swing.JPanel {
    
    private service_user servis = new DAO_User();
    private tablemod_user tblModel = new tablemod_user();
    
    static DefaultTableModel m, mod_p;
    private PopupMenu TambahUser;
    /**
     * Creates new form User
     */
    
    public User() {
        initComponents();
        
        tbl_User.setModel(tblModel);
        loadData();
        
//        settingTable();        
//        viewData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_User = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bt_hapus = new javax.swing.JButton();
        bt_tambahdata = new javax.swing.JButton();
        text_Cari = new javax.swing.JTextField();
        bt_cari = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        tambahUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_batal = new javax.swing.JButton();
        btn_simpanuser = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo_role = new javax.swing.JComboBox<>();
        txt_password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_fullname = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_notelp = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_iduser = new javax.swing.JTextField();
        ubahUser = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        bt_simpan1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtPassword1 = new javax.swing.JPasswordField();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataUser.setBackground(new java.awt.Color(255, 255, 255));
        dataUser.setPreferredSize(new java.awt.Dimension(600, 500));

        tbl_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_user", "username", "password", "fullname", "email", "no telp", "alamat"
            }
        ));
        tbl_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_UserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_User);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Data User");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bt_hapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_hapus.setText("Hapus");
        bt_hapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_tambahdata.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_tambahdata.setText("Tambah");
        bt_tambahdata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });

        bt_cari.setText("cari");
        bt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cariActionPerformed(evt);
            }
        });
        bt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_cariKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bt_cariKeyTyped(evt);
            }
        });

        bt_batal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_batal.setText("Batal");
        bt_batal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataUserLayout = new javax.swing.GroupLayout(dataUser);
        dataUser.setLayout(dataUserLayout);
        dataUserLayout.setHorizontalGroup(
            dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataUserLayout.createSequentialGroup()
                        .addGroup(dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(dataUserLayout.createSequentialGroup()
                                .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_cari)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );
        dataUserLayout.setVerticalGroup(
            dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cari)
                    .addComponent(text_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(dataUser, "card2");

        tambahUser.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tambah User");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_batal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_simpanuser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_simpanuser.setText("Simpan");
        btn_simpanuser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_simpanuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanuserActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Role");

        combo_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Admin", "Kasir" }));
        combo_role.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Id user");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Fullname");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Email");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("No telp");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Alamat");

        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        txt_fullname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fullnameActionPerformed(evt);
            }
        });

        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        txt_notelp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_notelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_notelpActionPerformed(evt);
            }
        });

        txt_alamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        txt_iduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_iduserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_iduser, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(txt_fullname)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(txt_password)
                    .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(combo_role, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addComponent(txt_notelp)
                                .addComponent(txt_alamat)))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_iduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(combo_role, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahUserLayout = new javax.swing.GroupLayout(tambahUser);
        tambahUser.setLayout(tambahUserLayout);
        tambahUserLayout.setHorizontalGroup(
            tambahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tambahUserLayout.createSequentialGroup()
                        .addGroup(tambahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(tambahUserLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_simpanuser, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahUserLayout.setVerticalGroup(
            tambahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(tambahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpanuser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(tambahUser, "card2");

        ubahUser.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tambah User");
        jLabel6.setToolTipText("");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Batal");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        bt_simpan1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_simpan1.setText("Simpan");
        bt_simpan1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpan1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Password");

        txtUsername1.setBackground(new java.awt.Color(204, 204, 204));
        txtUsername1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Username");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Role");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Admin", "Kasir" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPassword1.setBackground(new java.awt.Color(204, 204, 204));
        txtPassword1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassword1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(22, 22, 22)
                .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ubahUserLayout = new javax.swing.GroupLayout(ubahUser);
        ubahUser.setLayout(ubahUserLayout);
        ubahUserLayout.setHorizontalGroup(
            ubahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubahUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ubahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ubahUserLayout.createSequentialGroup()
                        .addGroup(ubahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(ubahUserLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bt_simpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 610, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ubahUserLayout.setVerticalGroup(
            ubahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ubahUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(ubahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        mainPanel.add(ubahUser, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        hapusData();
//        int n = tbl_User.getSelectedRow();
//        if (n != -1) {
//            int id = Integer.parseInt(tbl_User.getValueAt(n, 0).toString());
//            String username = tbl_User.getValueAt(n, 1).toString();
//
//            int opsi = JOptionPane.showConfirmDialog(this,
//                "Apakah Anda yakin ingin menghapus data " + username + "?",
//                "Hapus Data",
//                JOptionPane.YES_NO_OPTION);
//
//            if (opsi == JOptionPane.YES_OPTION) {
//                String Q = "DELETE FROM user WHERE id_user = ?";
//
//                try {
//                    Connection K = koneksi.Go();
//                    PreparedStatement ps = K.prepareStatement(Q);
//                    ps.setInt(1, id);
//                    ps.executeUpdate();
////                    viewData("");
//                    JOptionPane.showMessageDialog(this, "Data " + username + " telah terhapus");
//                } catch (SQLException e) {
//                    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
//                }
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus terlebih dahulu.");
//        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tambahUser);
        mainPanel.repaint();
        mainPanel.revalidate();
        txt_iduser.requestFocus();
        
        btn_simpanuser.setText("SIMPAN");
        txt_iduser.requestFocus();
//        txt_iduser.setText(servis.nomor());
        
        if(bt_tambahdata.getText().equals("UBAH"))
        {
            dataTabel();
        }
    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void btn_simpanuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanuserActionPerformed
      
        if (btn_simpanuser.getText().equals("TAMBAH")) {
            btn_simpanuser.setText("SIMPAN");
//            txt_iduser.setText(servis.nomor());
        } else if (btn_simpanuser.getText().equals("SIMPAN")) {
            simpanData();
        } else if (btn_simpanuser.getText().equals("PERBARUI")) {
            perbaruiData();
        }
//        String username = txt_iduser.getText();
//        String password = new String(txt_password.getPassword());
//        String role = jComboBox1.getSelectedItem().toString();
//
        
//        try {
//            Connection K = koneksi.Go();
//            PreparedStatement P = K.prepareStatement(Q);
//            P.setString(1, username);
//            P.setString(2, password);
//            P.setString(3, role);
//            P.executeUpdate();
//
//            
//            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
//            
//            txt_iduser.setText("");
//            txt_password.setText("");
//            jComboBox1.setSelectedIndex(0);
//            txt_iduser.requestFocus();
//           
//            viewData("");
//            
//            mainPanel.removeAll();
//            mainPanel.add(dataUser);
//            mainPanel.revalidate();
//            mainPanel.repaint();
//
//
//
//           
//        } catch (Exception e) {
//            e.printStackTrace();
//        }     
//        mainPanel.add(dataUser);
//        JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
//      
//
//    // Arahkan ke panel dataUser
//        mainPanel.removeAll();
//        mainPanel.add(tambahUser);
//        mainPanel.revalidate();
//        mainPanel.repaint();
    }//GEN-LAST:event_btn_simpanuserActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
        txt_fullname.requestFocus();
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void bt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cariActionPerformed
        // TODO add your handling code here:
        text_Cari.setText("");
//        cariData();
    }//GEN-LAST:event_bt_cariActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        // TODO add your handling code here:
//        viewData("");
    }//GEN-LAST:event_bt_batalActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bt_simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_simpan1ActionPerformed

    private void txtUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername1ActionPerformed

    private void txtPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassword1ActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
        txt_password.requestFocus();
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void tbl_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_UserMouseClicked
        // TODO add your handling code here:
        if (bt_tambahdata.getText().equals("TAMBAH")) {
            bt_tambahdata.setText("UBAH");
        }
        bt_hapus.setVisible(true);
        bt_batal.setVisible(true);
    }//GEN-LAST:event_tbl_UserMouseClicked

    private void txt_fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fullnameActionPerformed
        // TODO add your handling code here:
        txt_email.requestFocus();
    }//GEN-LAST:event_txt_fullnameActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
        txt_notelp.requestFocus();
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_notelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_notelpActionPerformed
        // TODO add your handling code here:
        txt_alamat.requestFocus();
    }//GEN-LAST:event_txt_notelpActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
        combo_role.requestFocus();
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void bt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_cariKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cariKeyPressed

    private void bt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_cariKeyTyped
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_bt_cariKeyTyped

    private void txt_iduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_iduserActionPerformed
        // TODO add your handling code here:
        txt_password.requestFocus();
    }//GEN-LAST:event_txt_iduserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_cari;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_simpan1;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_simpanuser;
    private javax.swing.JComboBox<String> combo_role;
    private javax.swing.JPanel dataUser;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel tambahUser;
    private javax.swing.JTable tbl_User;
    private javax.swing.JTextField text_Cari;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JTextField txtUsername1;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fullname;
    private javax.swing.JTextField txt_iduser;
    private javax.swing.JTextField txt_notelp;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    private javax.swing.JPanel ubahUser;
    // End of variables declaration//GEN-END:variables
     private void dataTabel(){
        dataUser.setVisible(false);
        tambahUser.setVisible(true);

        int row = tbl_User.getSelectedRow();
        jLabel2.setText("Perbarui Data User");

        txt_iduser.setEnabled(false);

        txt_iduser.setText(tbl_User.getModel().getValueAt(row, 1).toString());
        txt_username.setText(tbl_User.getModel().getValueAt(row, 2).toString());
        txt_password.setText(tbl_User.getModel().getValueAt(row, 3).toString());
        txt_fullname.setText(tbl_User.getModel().getValueAt(row, 4).toString());
        txt_email.setText(tbl_User.getModel().getValueAt(row, 5).toString());
        txt_notelp.setText(tbl_User.getModel().getValueAt(row, 6).toString());
        txt_alamat.setText(tbl_User.getModel().getValueAt(row, 7).toString());
        combo_role.setSelectedItem(tbl_User.getModel().getValueAt(row, 8).toString());

        aktif();
        btn_simpanuser.setText("PERBARUI");
        bt_batal.setVisible(true);
    }
    private void aktif(){
        txt_username.setEnabled(true);
        txt_password.setEnabled(true);
        txt_fullname.setEnabled(true);
        txt_email.setEnabled(true);
        txt_notelp.setEnabled(true);
        txt_alamat.setEnabled(true);
        combo_role.setEnabled(true);
    }
    private void loadData() {
        bt_hapus.setVisible(false);
        bt_batal.setVisible(false);
        List<model_user> list = servis.getData();
        tblModel.setData(list);
    }
    
    private void hapusData(){
        int index = tbl_User.getSelectedRow();
        if (index != -1) {
            model_user brg = tblModel.getData(tbl_User.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan di hapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                servis.hapusData(brg);
                tblModel.hapusData(index);
                loadData();
                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan di update");
        }
    }

    private void simpanData() {
        if (validasiInput() == true) {
            int id_user = Integer.parseInt(txt_iduser.getText());
            String nama_user = txt_username.getText();
            String password = txt_password.getText();
            String fullname = txt_fullname.getText();
            String email = txt_email.getText();
            String no = txt_notelp.getText();
            String alamat = txt_alamat.getText();
            String role = combo_role.getSelectedItem().toString();

            model_user brg = new model_user();
            brg.setId_user(id_user);
            brg.setUsername(nama_user);
            brg.setPassword(password);
            brg.setFullname(fullname);
            brg.setEmail(email);
            brg.setNo_telepon(no);
            brg.setAlamat(alamat);
            brg.setRole(role);

            servis.tambahData(brg);
            tblModel.tambahData(brg);
            loadData();
            resetForm();
            tampilPanel();
            btn_simpanuser.setText("TAMBAH");
        }
    }
    
    
    
    
    
    
    
    private void perbaruiData() {
        int index = tbl_User.getSelectedRow();
        if (index != -1) {
            model_user mod_user = tblModel.getData(tbl_User.convertRowIndexToModel(index));

            if (validasiInput() == true) {
                int id_user = Integer.parseInt(txt_iduser.getText());
                String nama_user = txt_username.getText();
                String password = txt_password.getText();
                String fullname = txt_fullname.getText();
                String email = txt_email.getText();
                String no = txt_notelp.getText();
                String alamat = txt_alamat.getText();
                String role = combo_role.getSelectedItem().toString();

                model_user brg = new model_user();

                brg.setId_user(id_user);
                brg.setUsername(nama_user);
                brg.setPassword(password);
                brg.setFullname(fullname);
                brg.setEmail(email);
                brg.setNo_telepon(no);
                brg.setAlamat(alamat);
                brg.setRole(role);

                servis.perbaruiData(brg);
                tblModel.perbaruiData(index, brg);
                loadData();
                resetForm();
                tampilPanel();
            }
        }
    }

    private void resetForm() {
        bt_tambahdata.requestFocus();
        bt_tambahdata.setText("TAMBAH");
        txt_iduser.setText("");
        txt_username.setText("");
        txt_password.setText("");
        txt_fullname.setText("");
        txt_email.setText("");
        txt_notelp.setText("");
        txt_alamat.setText("");
        combo_role.setSelectedItem(0);
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (txt_iduser.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Id User tidak boleh kosong");
        } else if (txt_username.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong");
        } else if (txt_password.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email tidak boleh kosong");
        } else if (txt_fullname.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No Telepon tidak boleh kosong");
        } else if (txt_email.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
        } else if (txt_notelp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong");
        } else if (txt_alamat.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong");
        } else if (combo_role.getSelectedItem().equals(null)) {
            JOptionPane.showMessageDialog(null, "Role produk tidak boleh kosong");
        } else {
            valid = true;
        }
        return valid;
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new User());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void cariData() {
        List<model_user> list = servis.cariData(text_Cari.getText());
        tblModel.setData(list);
    }
}
















//    private void settingTable() {
//        m = (DefaultTableModel) tbl_User.getModel();        
//
//        // Mengatur lebar kolom sesuai jumlah kolom yang ada
//        tbl_User.getColumnModel().getColumn(0).setMinWidth(50);   // id
//        tbl_User.getColumnModel().getColumn(0).setMaxWidth(70);
//
//        tbl_User.getColumnModel().getColumn(0).setMinWidth(50);  // username
//        tbl_User.getColumnModel().getColumn(0).setMaxWidth(70);
//
//        tbl_User.getColumnModel().getColumn(2).setMinWidth(350);  // password
//        tbl_User.getColumnModel().getColumn(2).setMaxWidth(500);
//        
//        tbl_User.getColumnModel().getColumn(2).setMinWidth(350);  // password
//        tbl_User.getColumnModel().getColumn(2).setMaxWidth(500);
//        
//        tbl_User.getColumnModel().getColumn(2).setMinWidth(350);  // password
//        tbl_User.getColumnModel().getColumn(2).setMaxWidth(500);
//        
//        tbl_User.getColumnModel().getColumn(2).setMinWidth(350);  // password
//        tbl_User.getColumnModel().getColumn(2).setMaxWidth(500);
//
//    
//       
//    }
//    
//    public static void viewData(String where) {
//        try {
//            // Hapus semua baris di model tabel
//            for (int i = m.getRowCount() - 1; i >= 0; i--) {
//                m.removeRow(i);
//            }
//
//            Connection K = koneksi.Go();
//            Statement S = K.createStatement();
//            String Q = "SELECT * FROM user " + where;
//            ResultSet R = S.executeQuery(Q);
//            int no = 1;
//            while (R.next()) {
//                int id = R.getInt("id_user");
//                String username = R.getString("username");
//                String password = R.getString("password");
//                String level = R.getString("role");
//                String fullname = R.getString("fullname");
//                String email = R.getString("email");
//                String no_telepon = R.getString("no_telepon");
//                String alamat = R.getString("alamat");
//
//                Object[] D = {id, username, level, password, fullname, email, no_telepon, alamat};
//                m.addRow(D);
//
//                no++;
//            }
//        } catch (SQLException e) {
//            // Error handling
//            JOptionPane.showMessageDialog(null, "Error fetching data: " + e.getMessage());
//        }
//    }
//
//
//   
//
//        private void cariData() {
//           String keyword = txtCari.getText().trim();
//           if (!keyword.isEmpty()) {
//               String where = "WHERE username LIKE '%" + keyword + "%' OR role LIKE '%" + keyword + "%'";
//               viewData(where);
//           } else {
//               viewData(""); // Jika keyword kosong, tampilkan semua data
//           }
//       }
//
//    private static class e {
//
//        private static String getMessage() {
//            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//        }
//
//        public e() {
//        }
//    }

   
