package main;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmdsaif
 */
public class AdminPage1 extends javax.swing.JFrame {

//    Profile p;
//    private Profile P;
//    private static DefaultTableModel m = new DefaultTableModel();
//
//    public Connection con;
//    public Statement stm;
//    public ResultSet rs;
//    
//    public AdminPage1() {
//        initComponents();
//        settingTable();
//        viewData("");
//    }
//
//    AdminPage1(Profile P) {
//        this(P);
//    }
//
//    AdminPage1(Profile P) {
//        initComponents();
//        this.p = P;
//        labelUser.setText(P.getUsername());
//        settingTable();
//        viewData("");
//    }
//
//    public AdminPage1(Profile P) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        jLabel1 = new javax.swing.JLabel();
//        labelUser = new javax.swing.JLabel();
//        jTabbedPane1 = new javax.swing.JTabbedPane();
//        jPanel2 = new javax.swing.JPanel();
//        jPanel5 = new javax.swing.JPanel();
//        btnTambah = new javax.swing.JButton();
//        jButton2 = new javax.swing.JButton();
//        btnHapus = new javax.swing.JButton();
//        txtSearch = new javax.swing.JTextField();
//        btnPencarian = new javax.swing.JButton();
//        btnRefresh = new javax.swing.JButton();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        tbluser = new javax.swing.JTable();
//        jPanel3 = new javax.swing.JPanel();
//        jPanel4 = new javax.swing.JPanel();
//        jMenuBar1 = new javax.swing.JMenuBar();
//        btnSettings = new javax.swing.JMenu();
//        btnLogout = new javax.swing.JMenuItem();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
//
//        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
//        jLabel1.setText("Welcome");
//
//        labelUser.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addGap(23, 23, 23)
//                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(447, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addContainerGap(29, Short.MAX_VALUE)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel1)
//                    .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(23, 23, 23))
//        );
//
//        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
//
//        jPanel2.setLayout(new java.awt.BorderLayout());
//
//        jPanel5.setBackground(new java.awt.Color(102, 153, 255));
//
//        btnTambah.setText("Tambah");
//        btnTambah.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnTambahActionPerformed(evt);
//            }
//        });
//
//        jButton2.setText("Ubah");
//        jButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton2ActionPerformed(evt);
//            }
//        });
//
//        btnHapus.setText("Hapus");
//        btnHapus.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnHapusActionPerformed(evt);
//            }
//        });
//
//        txtSearch.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtSearchActionPerformed(evt);
//            }
//        });
//
//        btnPencarian.setText("Cari");
//        btnPencarian.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnPencarianActionPerformed(evt);
//            }
//        });
//
//        btnRefresh.setText("Refresh");
//        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnRefreshActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
//        jPanel5.setLayout(jPanel5Layout);
//        jPanel5Layout.setHorizontalGroup(
//            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel5Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
//                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addComponent(btnPencarian)
//                .addGap(31, 31, 31))
//        );
//        jPanel5Layout.setVerticalGroup(
//            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel5Layout.createSequentialGroup()
//                .addGap(29, 29, 29)
//                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(btnPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addContainerGap(35, Short.MAX_VALUE))
//        );
//
//        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);
//
//        tbluser.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null}
//            },
//            new String [] {
//                "ID", "Username", "Password", "Role"
//            }
//        ) {
//            Class[] types = new Class [] {
//                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
//            };
//
//            public Class getColumnClass(int columnIndex) {
//                return types [columnIndex];
//            }
//        });
//        jScrollPane1.setViewportView(tbluser);
//
//        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);
//
//        jTabbedPane1.addTab("Data User", jPanel2);
//
//        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
//        jPanel3.setLayout(jPanel3Layout);
//        jPanel3Layout.setHorizontalGroup(
//            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 782, Short.MAX_VALUE)
//        );
//        jPanel3Layout.setVerticalGroup(
//            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 373, Short.MAX_VALUE)
//        );
//
//        jTabbedPane1.addTab("Data Produk", jPanel3);
//
//        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
//        jPanel4.setLayout(jPanel4Layout);
//        jPanel4Layout.setHorizontalGroup(
//            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 782, Short.MAX_VALUE)
//        );
//        jPanel4Layout.setVerticalGroup(
//            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 373, Short.MAX_VALUE)
//        );
//
//        jTabbedPane1.addTab("Data Transaksi", jPanel4);
//
//        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);
//
//        btnSettings.setText("Settings");
//        btnSettings.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnSettingsActionPerformed(evt);
//            }
//        });
//
//        btnLogout.setText("Logout");
//        btnLogout.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnLogoutActionPerformed(evt);
//            }
//        });
//        btnSettings.add(btnLogout);
//
//        jMenuBar1.add(btnSettings);
//
//        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
//        TambahUser T = new TambahUser(this, true);
//        T.setVisible(true); 
//    }//GEN-LAST:event_btnTambahActionPerformed

//    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        // TODO add your handling code here:
//        int n = tbluser.getSelectedRow();
//        if (n != -1) {
//            int id = Integer.parseInt(tbluser.getValueAt(n, 0).toString());
//            String username = tbluser.getValueAt(n, 1).toString();
//            String password = tbluser.getValueAt(n, 2).toString();
//            String level = tbluser.getValueAt(n, 3).toString();
//
//            UbahUser U = new UbahUser(this, true);
//            U.setIdUser(id); 
//            U.setUsername(username);
//            U.setPassword(password); 
//            U.setLevel(level);
//            U.loadUserData(); // Memuat data ke komponen UI
//            U.setVisible(true); 
//        } else {
//            JOptionPane.showMessageDialog(this, "Anda belum memilih data");
//        }
//    }//GEN-LAST:event_jButton2ActionPerformed
//
//    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
//        // TODO add your handling code here:
//        int n = tbluser.getSelectedRow();
//        if (n != -1) {
//        int id = Integer.parseInt(tbluser.getValueAt(n, 0).toString());
//        String username = tbluser.getValueAt(n, 1).toString();
//
//        int opsi = JOptionPane.showConfirmDialog(this, 
//                "Apakah Anda yakin ingin menghapus data " + username + "?", 
//                "Hapus Data", 
//                JOptionPane.YES_NO_OPTION);
//
//        if (opsi == JOptionPane.YES_OPTION) {
//            String Q = "DELETE FROM users WHERE user_id = ?";
//
//            try {
//                Connection K = Koneksi.Go();
//                PreparedStatement ps = K.prepareStatement(Q);
//                ps.setInt(1, id);
//                ps.executeUpdate();
//                viewData(""); 
//                JOptionPane.showMessageDialog(this, "Data " + username + " telah terhapus");
//                Logging.saveLog("berhasil menghapus user " + username);
//            } catch (SQLException e) {
//                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
//            }
//        }
//        } else {
//        JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus terlebih dahulu.");
//        }
//    }//GEN-LAST:event_btnHapusActionPerformed
//
//    private void btnPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPencarianActionPerformed
//        // TODO add your handling code here:
//        String keyword = txtSearch.getText().trim(); // Mendapatkan kata kunci dari JTextField
//        String whereClause = "";
//
//        if (!keyword.isEmpty()) {
//            // Membuat klausa WHERE untuk pencarian berdasarkan username
//            whereClause = "WHERE username LIKE '%" + keyword + "%'";
//        }
//
//        viewData(whereClause);
//        txtSearch.setText("");
//    }//GEN-LAST:event_btnPencarianActionPerformed
//
//    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
//        // TODO add your handling code here:
//        viewData("");
//    }//GEN-LAST:event_btnRefreshActionPerformed
//
//    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_btnSettingsActionPerformed
//
//    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
//        // TODO add your handling code here:
//        Login menu = new Login();
//        menu.setVisible(true);
//        setVisible(false);
//    }//GEN-LAST:event_btnLogoutActionPerformed
//
//    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_txtSearchActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
////                new AdminPage().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton btnHapus;
//    private javax.swing.JMenuItem btnLogout;
//    private javax.swing.JButton btnPencarian;
//    private javax.swing.JButton btnRefresh;
//    private javax.swing.JMenu btnSettings;
//    private javax.swing.JButton btnTambah;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JMenuBar jMenuBar1;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JPanel jPanel2;
//    private javax.swing.JPanel jPanel3;
//    private javax.swing.JPanel jPanel4;
//    private javax.swing.JPanel jPanel5;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JTabbedPane jTabbedPane1;
//    private javax.swing.JLabel labelUser;
//    private javax.swing.JTable tbluser;
//    private javax.swing.JTextField txtSearch;
//    // End of variables declaration//GEN-END:variables
//
//    public static void viewData(String where) {
//        try {
//            // Menghapus semua baris sebelumnya di tabel
//            for (int i = m.getRowCount() - 1; i >= 0; i--) {
//                m.removeRow(i);
//            }
//
//            Connection K = Koneksi.Go();
//            Statement S = K.createStatement();
//
//            // Menyusun query SQL dengan klausa WHERE jika ada
//            String Q = "SELECT * FROM users";
//            if (!where.isEmpty()) {
//                Q += " " + where; // Menambahkan klausa WHERE dari parameter
//            }
//
//            ResultSet R = S.executeQuery(Q);
//            int no = 1;
//            while (R.next()) {
//                int id = R.getInt("user_id");
//                String username = R.getString("username");
//                String password = R.getString("password");
//                String level = R.getString("role");
//
//                Object[] D = {id, username, password, level};
//                m.addRow(D);
//                no++;
//            }
//            Logging.saveLog("Berhasil Menampilkan data User");
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
//}
//
//
//private void settingTable() {
//        m = (DefaultTableModel) tbluser.getModel();
//        tbluser.getColumnModel().getColumn(0).setMinWidth(50);
//        tbluser.getColumnModel().getColumn(0).setMaxWidth(70);
//
//        tbluser.getColumnModel().getColumn(0).setMinWidth(50);
//        tbluser.getColumnModel().getColumn(0).setMaxWidth(70);
////        tbluser.getColumnModel().getColumn(1).setMinWidth(0);
////        tbluser.getColumnModel().getColumn(1).setMaxWidth(0);
//
//        tbluser.getColumnModel().getColumn(2).setMinWidth(350);
//        tbluser.getColumnModel().getColumn(2).setMaxWidth(500);
//    
//        
////        mod_p = (DefaultTableModel) tblDataProduk.getModel();        
////        tblDataProduk.getColumnModel().getColumn(0).setMinWidth(50);
////        tblDataProduk.getColumnModel().getColumn(0).setMaxWidth(70);
////
////        tblDataProduk.getColumnModel().getColumn(1).setMinWidth(0);
////        tblDataProduk.getColumnModel().getColumn(1).setMaxWidth(0);      
//    
//    }
}}